/**
 * TRIDENT MULTI-MODE — ARTIFACT GENERATOR
 * 
 * Generates structured markdown artifacts for each mode.
 * Provides consistent output format across all Trident plugins.
 */

export interface ArtifactConfig {
  mode: string;
  layer: number;
  layerName: string;
  thinking: string;
  timestamp?: Date;
}

export class ArtifactGenerator {
  private artifacts: Map<string, string> = new Map();
  private currentArtifactKey: string | null = null;

  /**
   * Create a new artifact for a layer
   */
  createArtifact(config: ArtifactConfig, content: string): string {
    const timestamp = config.timestamp || new Date();
    const date = timestamp.toISOString().split('T')[0];
    const key = `${config.mode}_LAYER${config.layer}_${date}.md`;

    const fullArtifact = this.formatArtifact(config, content);
    this.artifacts.set(key, fullArtifact);
    this.currentArtifactKey = key;

    return key;
  }

  /**
   * Format an artifact with standard header
   */
  private formatArtifact(config: ArtifactConfig, content: string): string {
    const timestamp = config.timestamp || new Date();
    const date = timestamp.toISOString().split('T')[0];
    const time = timestamp.toISOString().split('T')[1].split('.')[0];

    return `# ${config.mode} — ${config.layerName}

**Layer:** ${config.layer}
**Date:** ${date} ${time}
**Thinking:** ${config.thinking}

---

${content}

---

*Generated by Trident Brain v1.0 - ${config.mode}*
`;
  }

  /**
   * Generate layer-specific artifact content
   */
  generateLayerContent(
    layer: number,
    layerName: string,
    data: Record<string, string | string[]>
  ): string {
    switch (layer) {
      case 1:
        return this.generateLayer1Content(layerName, data);
      case 2:
        return this.generateLayer2Content(layerName, data);
      case 3:
        return this.generateLayer3Content(layerName, data);
      case 4:
        return this.generateLayer4Content(layerName, data);
      case 5:
        return this.generateLayer5Content(layerName, data);
      case 6:
        return this.generateLayer6Content(layerName, data);
      default:
        return this.generateDefaultContent(layerName, data);
    }
  }

  /**
   * Layer 1: Initial/Collection content
   */
  private generateLayer1Content(layerName: string, data: Record<string, string | string[]>): string {
    const items = Array.isArray(data.items) ? data.items : [];
    return `## ${layerName}

### Sources Collected
${items.map((item: string) => `- ${item}`).join('\n')}

### Summary
${data.summary || 'No summary provided.'}

### Key Findings
${data.findings || 'No findings yet.'}`;
  }

  /**
   * Layer 2: Scoring/Ranking content
   */
  private generateLayer2Content(layerName: string, data: Record<string, string | string[]>): string {
    const scores = Array.isArray(data.scores) ? data.scores : [];
    return `## ${layerName}

### Priority Ranking
${scores.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}

### Top Priority
${data.topPriority || 'No priority selected.'}

### Reasoning
${data.reasoning || 'No reasoning provided.'}`;
  }

  /**
   * Layer 3: Compression/Sequence content
   */
  private generateLayer3Content(layerName: string, data: Record<string, string | string[]>): string {
    return `## ${layerName}

### Compressed Summary
${data.summary || 'No summary available.'}

### Token Budget
- Budget: ${data.budget || 2000} tokens
- Used: ${data.used || 0} tokens

### Compression Applied
${data.compression || 'No compression applied.'}`;
  }

  /**
   * Layer 4: Injection/Context Library content
   */
  private generateLayer4Content(layerName: string, data: Record<string, string | string[]>): string {
    const sections = Array.isArray(data.sections) ? data.sections : [];
    return `## ${layerName}

### T0-Ready Output

#### Sections
${sections.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}

#### Formatted Output
\`\`\`
${data.output || 'No output available.'}
\`\`\``;
  }

  /**
   * Layer 5: Meta-reflection content
   */
  private generateLayer5Content(layerName: string, data: Record<string, string | string[]>): string {
    const patterns = Array.isArray(data.patterns) ? data.patterns : [];
    return `## ${layerName}

### Patterns Identified
${patterns.map((p: string, i: number) => `${i + 1}. ${p}`).join('\n')}

### Systemic Issues
${data.systemic || 'No systemic issues identified.'}

### Lessons Learned
${data.lessons || 'No lessons recorded.'}`;
  }

  /**
   * Layer 6: Verification content
   */
  private generateLayer6Content(layerName: string, data: Record<string, string | string[]>): string {
    return `## ${layerName}

### Verification Command
\`\`\`
${data.command || 'No command specified.'}
\`\`\`

### Expected Output
\`\`\`
${data.expected || 'No expected output specified.'}
\`\`\`

### Actual Result
${data.actual || 'Not yet verified.'}

### Status
${data.status || 'PENDING'}`;
  }

  /**
   * Default content generator
   */
  private generateDefaultContent(layerName: string, data: Record<string, string | string[]>): string {
    return `## ${layerName}

### Content
${Object.entries(data).map(([k, v]) => `**${k}:** ${Array.isArray(v) ? v.join(', ') : v}`).join('\n')}`;
  }

  /**
   * Generate a full report combining all layers
   */
  generateFullReport(mode: string, artifacts: Map<string, string>): string {
    let report = `# ${mode.toUpperCase()} — FULL REPORT\n\n`;
    report += `**Generated:** ${new Date().toISOString()}\n\n`;
    report += `---\n\n`;

    for (const [key, content] of artifacts) {
      report += `## ${key}\n\n`;
      report += content;
      report += `\n\n---\n\n`;
    }

    return report;
  }

  /**
   * Get all artifacts
   */
  getArtifacts(): Map<string, string> {
    return new Map(this.artifacts);
  }

  /**
   * Get artifact by key
   */
  getArtifact(key: string): string | undefined {
    return this.artifacts.get(key);
  }

  /**
   * Get current artifact
   */
  getCurrentArtifact(): string | undefined {
    return this.currentArtifactKey ? this.artifacts.get(this.currentArtifactKey) : undefined;
  }

  /**
   * Clear all artifacts
   */
  clear(): void {
    this.artifacts.clear();
    this.currentArtifactKey = null;
  }

  /**
   * Save artifact to file path
   */
  saveArtifact(key: string, filePath: string): void {
    const content = this.artifacts.get(key);
    if (content) {
      // Note: actual file writing should be done via tool hook
      console.log(`[ArtifactGenerator] Would save ${key} to ${filePath}`);
    }
  }
}